Inc/arith_lib.h File Reference
This module contains some arithmetic functions.
#include <stdbool.h>
Functions
bool overflowAdd (int arg1, int arg2)
bool overflowSub (int arg1, int arg2)
bool overflowMult (int arg1, int arg2)
bool overflowDiv (int arg1, int arg2)
void printNumber (int v)
Detailed Description
This module contains some arithmetic functions.
Author
Franz Korf, HAW Hamburg
Date
Sep 2023
Definition in file arith_lib.h.
Function Documentation
overflowAdd()
bool overflowAdd (int arg1, int arg2)
Definition at line 54 of file arith_lib.c.
Referenced by handleToken(), and overflowSub().
overflowDiv()
bool overflowDiv (int arg1, int arg2) [extern]
Definition at line 48 of file arith_lib.c.
Referenced by handleToken().
overflowMult()
bool overflowMult (int arg1, int arg2) [extern]
Definition at line 30 of file arith_lib.c.
Referenced by handleToken().
overflowSub()
bool overflowSub (int arg1, int arg2)
Definition at line 66 of file arith_lib.c.
Referenced by handleToken().
printNumber()
void printNumber (int v) [extern]
Definition at line 14 of file arith_lib.c.
Referenced by handleToken().