Src/arith_lib.c File Reference
This modules contains some arithmetic functions.
#include "arith_lib.h"
#include "display.h"
#include <stdlib.h>
#include <limits.h>
Macros
#define PRT_BUF_SIZE 16
Functions
void printNumber (int v)
bool overflowMult (int arg1, int arg2)
bool overflowDiv (int arg1, int arg2)
bool overflowAdd (int arg1, int arg2)
bool overflowSub (int arg1, int arg2)
Detailed Description
This modules contains some arithmetic functions.
Author
Franz Korf, HAW Hamburg
Date
Sep 2023
Definition in file arith_lib.c.
Macro Definition Documentation
PRT_BUF_SIZE
#define PRT_BUF_SIZE 16
Definition at line 13 of file arith_lib.c.
Referenced by printNumber().
Function Documentation
overflowAdd()
bool overflowAdd (int arg1, int arg2)
Definition at line 54 of file arith_lib.c.
Referenced by handleToken(), and overflowSub().
overflowDiv()
bool overflowDiv (int arg1, int arg2)
Definition at line 48 of file arith_lib.c.
Referenced by handleToken().
overflowMult()
bool overflowMult (int arg1, int arg2)
Definition at line 30 of file arith_lib.c.
Referenced by handleToken().
overflowSub()
bool overflowSub (int arg1, int arg2)
Definition at line 66 of file arith_lib.c.
Referenced by handleToken().
printNumber()
void printNumber (int v)
Definition at line 14 of file arith_lib.c.
Referenced by handleToken().