Inc/display.h File Reference
Header file of display module.
#include <stdbool.h>
Functions
void initDisplay (void)
void setErrMode (void)
void setNormalMode (void)
void printStdout (char *msg)
void printToEchoLine (char c)
void clearEchoTerm (void)
void clearStdout (void)
bool isBottomLine (void)
Detailed Description
Header file of display module.
Author
Franz Korf, HAW Hamburg
Date
Mar 2016
Definition in file display.h.
Function Documentation
clearEchoTerm()
void clearEchoTerm (void) [extern]
Definition at line 25 of file display.c.
Referenced by initDisplay(), and nextToken().
clearStdout()
void clearStdout (void) [extern]
Definition at line 21 of file display.c.
Referenced by handleToken(), and initDisplay().
initDisplay()
void initDisplay (void)
Definition at line 33 of file display.c.
Referenced by main().
isBottomLine()
bool isBottomLine (void) [extern]
Definition at line 65 of file display.c.
Referenced by handleToken().
printStdout()
void printStdout (char * msg) [extern]
Definition at line 29 of file display.c.
Referenced by errHandler(), handleToken(), and printNumber().
printToEchoLine()
void printToEchoLine (char c) [extern]
Definition at line 49 of file display.c.
Referenced by nextToken().
setErrMode()
void setErrMode (void) [extern]
Definition at line 55 of file display.c.
Referenced by errHandler().
setNormalMode()
void setNormalMode (void) [extern]
Definition at line 60 of file display.c.
Referenced by clearSystem(), and handleToken().