Src/display.c File Reference
This modules implements a simple output module. It places two terminals in the terminal area of keypad. One terminal will be used for standard output. The other one echos pressed digit keys.
#include "display.h"
#include <stdlib.h>
#include "terminal.h"
#include "LCD_GUI.h"
#include "LCD_Touch.h"
#include "keypad.h"
Functions
void clearStdout (void)
void clearEchoTerm (void)
void printStdout (char *m)
void initDisplay (void)
void printToEchoLine (char c)
void setErrMode (void)
void setNormalMode (void)
bool isBottomLine (void)
Variables
static Terminal stdoutTerm = INVALID_TERM
static Terminal echoTerm = INVALID_TERM
Detailed Description
This modules implements a simple output module. It places two terminals in the terminal area of keypad. One terminal will be used for standard output. The other one echos pressed digit keys.
Author
Franz Korf, HAW Hamburg
Date
Mar 2016
Definition in file display.c.
Function Documentation
clearEchoTerm()
void clearEchoTerm (void)
Definition at line 25 of file display.c.
Referenced by initDisplay(), and nextToken().
clearStdout()
void clearStdout (void)
Definition at line 21 of file display.c.
Referenced by handleToken(), and initDisplay().
initDisplay()
void initDisplay (void)
Definition at line 33 of file display.c.
Referenced by main().
isBottomLine()
bool isBottomLine (void)
Definition at line 65 of file display.c.
Referenced by handleToken().
printStdout()
void printStdout (char * m)
Definition at line 29 of file display.c.
Referenced by errHandler(), handleToken(), and printNumber().
printToEchoLine()
void printToEchoLine (char c)
Definition at line 49 of file display.c.
Referenced by nextToken().
setErrMode()
void setErrMode (void)
Definition at line 55 of file display.c.
Referenced by errHandler().
setNormalMode()
void setNormalMode (void)
Definition at line 60 of file display.c.
Referenced by clearSystem(), and handleToken().
Variable Documentation
echoTerm
Terminal echoTerm = INVALID_TERM [static]
Definition at line 19 of file display.c.
Referenced by clearEchoTerm(), initDisplay(), and printToEchoLine().
stdoutTerm
Terminal stdoutTerm = INVALID_TERM [static]
Definition at line 18 of file display.c.
Referenced by clearStdout(), initDisplay(), isBottomLine(), printStdout(), setErrMode(), and setNormalMode().