Inc/int_stack.h File Reference
Header file of the int_stack module.
Functions
void initStack (void)
This function initializes / resets the stack.
int push (int value)
This function pushs an int value on the stack.
int pop (int *value)
This function pops an element for the stack.
int elemAt (int pos, int *value)
This function assigns stack element at position pos to *value.
Detailed Description
Header file of the int_stack module.
Author
Franz Korf, HAW Hamburg
Date
Mar 2016
Definition in file int_stack.h.
Function Documentation
elemAt()
int elemAt (int pos, int * value) [extern]
This function assigns stack element at position pos to *value.
Parameters
pos Position of element to be selected (pos == 0 : top of stack will be assigned).
value The address to which the element will be written.
Returns
Upon successful completion, a value of 0 is returned. Otherwise, a value of -1 is returned and the global integer variable errno is set to indicate the error.
Definition at line 40 of file int_stack.c.
Referenced by handleToken().
initStack()
void initStack (void) [extern]
This function initializes / resets the stack.
Returns
void
Definition at line 22 of file int_stack.c.
Referenced by clearSystem().
pop()
int pop (int * value) [extern]
This function pops an element for the stack.
Parameters
value The address to which pop should write the top element of the stack.
Returns
Upon successful completion, a value of 0 is returned. Otherwise, a value of -1 is returned and the global integer variable errno is set to indicate the error.
Definition at line 34 of file int_stack.c.
Referenced by handleToken().
push()
int push (int value) [extern]
This function pushs an int value on the stack.
Parameters
value The value that will be pushed on the stack.
Returns
Upon successful completion, a value of 0 is returned. Otherwise, a value of -1 is returned and the global integer variable errno is set to indicate the error.
Definition at line 28 of file int_stack.c.
Referenced by handleToken().