Src/main.c File Reference
Main program body and control module of RPN calculator. Modules are structured according to MVC (model view control) design. This solution bases on the RPN calculatr for the old TI Board.
#include "init.h"
#include "scanner.h"
#include "display.h"
#include "arith_lib.h"
#include "int_stack.h"
Functions
static void clearSystem (void)
static void errHandler (char *msg)
static void handleToken (void)
int main (void)
Detailed Description
Main program body and control module of RPN calculator. Modules are structured according to MVC (model view control) design. This solution bases on the RPN calculatr for the old TI Board.
Author
Franz Korf HAW-Hamburg
Version
V0.5
Date
2020-08-17
Definition in file main.c.
Function Documentation
clearSystem()
void clearSystem (void) [static]
Definition at line 19 of file main.c.
Referenced by errHandler(), and handleToken().
errHandler()
void errHandler (char * msg) [static]
Definition at line 24 of file main.c.
Referenced by handleToken(), and main().
handleToken()
void handleToken (void) [static]
Definition at line 44 of file main.c.
Referenced by main().
main()
int main (void)
Definition at line 114 of file main.c.