Src/scanner.c File Reference
This module implements a simple scanner for keypad input.
#include "scanner.h"
#include "display.h"
#include "keypad.h"
#include "token.h"
Functions
static char nextChar (void)
T_token nextToken (void)
Detailed Description
This module implements a simple scanner for keypad input.
Author
Franz Korf, HAW Hamburg
Date
Mar 2016
Definition in file scanner.c.
Function Documentation
nextChar()
char nextChar (void) [inline], [static]
Definition at line 20 of file scanner.c.
Referenced by nextToken().
nextToken()
T_token nextToken (void)
Definition at line 24 of file scanner.c.
Referenced by errHandler(), and handleToken().